In [1]:
import numpy as np

# Q 1

In [4]:
Data1 = np.array([1,3,9,12,18])
Data1

array([ 1,  3,  9, 12, 18])

In [6]:
Data2 = np.array([[1,5,2,0],[3,6,4,7]])
Data2

array([[1, 5, 2, 0],
       [3, 6, 4, 7]])

In [9]:
Data3 = np.array([[1,5,2,0],[3,6,4,7]], dtype= '<U1')
Data3

array([['1', '5', '2', '0'],
       ['3', '6', '4', '7']], dtype='<U1')

In [11]:
Data4 = np.array([[11,52,20,50],[34,61,43,17]])
Data4

array([[11, 52, 20, 50],
       [34, 61, 43, 17]])

# Q2

In [12]:
Data1+Data1

array([ 2,  6, 18, 24, 36])