In [2]:
import numpy as np

In [3]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
arr2.shape

# DTYPE

In [4]:
arr1.dtype

dtype('float64')

In [6]:
arr2 = np.array([1,3,5,7,9])

In [7]:
arr2.dtype

dtype('int32')

In [8]:
arr3= np.array([1,2,3] , dtype = np.float64)
arr3

array([1., 2., 3.])

In [9]:
arr4= np.array([1,2,3] , dtype = np.int32)
arr4

array([1, 2, 3])

In [10]:
arr3.dtype

dtype('float64')

In [11]:
arr4.dtype

dtype('int32')

# np.zeroes

In [12]:
np.zeros(10 , dtype= np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

2D array

In [15]:
np.zeros((3,6) , dtype = np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
np.empty((2,3,2))

array([[[6.80425344e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.18831764e-312, 2.17766519e-076]],

       [[2.67900862e+184, 3.96399654e-061],
        [6.52190405e-038, 4.11582325e+179],
        [2.23078330e+160, 2.17530532e-076]]])

# arange

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# array

In [18]:
np.array([1,8,9])

array([1, 8, 9])

In [19]:
np.array((1,8,9))

array([1, 8, 9])

# ones and ones_like

In [20]:
np.ones((2,3) , dtype =np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
tooba = np.array([[[1,2],[3,4],[5,6]]])
print(tooba)
np.ones_like(tooba)

[[[1 2]
  [3 4]
  [5 6]]]


array([[[1, 1],
        [1, 1],
        [1, 1]]])

# zeros, zeros_like

In [22]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
tooba = np.array([[[1,2],[3,4],[5,6]]])
print(tooba)
np.zeros_like(tooba)

[[[1 2]
  [3 4]
  [5 6]]]


array([[[0, 0],
        [0, 0],
        [0, 0]]])

# empty, empty_like

In [24]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# eye 

## np.eye(n, m, dtype, k for shift)

In [25]:
np.eye(3,4 ,dtype =np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [26]:
np.eye(3,4 ,dtype =np.int32 , k=1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

np.eye(3,4 ,dtype =np.int32 , k=2)

# identity dig me 0s

In [27]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

# Type Conversion for ndarrays

In [28]:
a= np.array([4,5,6])
a.dtype

dtype('int32')

In [29]:
b= a.astype(np.float32)
b.dtype

dtype('float32')

In [30]:
c= np.array([1.4, 7.8])
c.dtype

dtype('float64')

In [31]:
d= c.astype(np.int32)
d.dtype

dtype('int32')

In [32]:
d

array([1, 7])

In [33]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

[ 1.25 -9.6  42.  ]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Operations between Arrays and Scalars

In [34]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [35]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

## Basic Indexing and Slicing

In [36]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
arr


[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [37]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [38]:
arr_slice = arr[5:8]

In [39]:
arr_slice

array([12, 12, 12])

In [40]:
 arr_slice[1] = 12345

In [41]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 
12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
 arr3d[0]


array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Indexing with slices

In [47]:
r= np.array([0,1,2,3,4,64,64,64,8,9])
r

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [48]:
r[1:6]

array([ 1,  2,  3,  4, 64])

### Higher dimensional objects give more options as one or more axes can be sliced and also integers can be mixed. Consider the 2D array above, arr2d. Slicing this array is a bit different:


In [55]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr2d[:2 , 1:]

array([[2, 3],
       [5, 6]])

In [60]:
 arr2d[1, :2]

array([4, 5])

In [61]:
 arr2d[2, :1]


array([7])

In [64]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [66]:
arr2d[:2, 1:] = 0

# BROADCASTING

In [67]:
w = np.arange(5)
w

array([0, 1, 2, 3, 4])

In [68]:
w*4

array([ 0,  4,  8, 12, 16])

In [69]:
arr = np.random.randn(4, 3)
arr

array([[-0.31674131, -1.55140933, -0.25306875],
       [ 0.78221694,  1.02811293,  0.0328281 ],
       [ 1.0570636 ,  0.15180299, -1.77979705],
       [-1.68949164, -0.5633743 , -2.01148083]])

In [70]:
 arr.mean(0)

array([-0.0417381 , -0.23371693, -1.00287963])

In [71]:
demeaned = arr - arr.mean(0)
demeaned 

array([[-0.27500321, -1.3176924 ,  0.74981088],
       [ 0.82395504,  1.26182986,  1.03570773],
       [ 1.0988017 ,  0.38551992, -0.77691741],
       [-1.64775354, -0.32965738, -1.00860119]])

In [72]:
 demeaned.mean(0)

array([5.55111512e-17, 4.16333634e-17, 5.55111512e-17])

# Setting Array Values by Broadcasting


In [73]:
arr = np.zeros((4, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
arr[:] = 5 
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [77]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis] 
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [78]:
arr[:2] = [[-1.37], [0.509]] 
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

# Boolean Indexing

In [79]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 
'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [80]:
 data = np.random.randn(7, 4)
data

array([[ 1.50408051e+00,  9.62538827e-01, -9.68314855e-01,
        -3.82285822e-01],
       [-1.58100177e-01,  2.51850376e-01, -6.13279774e-01,
        -1.58432387e+00],
       [ 6.11326212e-01, -2.51068828e+00, -1.51057456e+00,
         4.53057350e-01],
       [-5.00265634e-01, -1.38378416e-01, -3.21998493e-01,
        -1.43599957e-01],
       [ 6.27746532e-04, -2.71728206e-02, -1.02827154e+00,
        -3.50335906e-01],
       [ 3.52062063e-01, -1.76159171e+00,  1.85921998e-03,
         1.38992412e+00],
       [ 5.13989437e-01, -3.71683998e-01, -1.42375092e+00,
        -4.70270654e-01]])

In [83]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [84]:
data


array([[ 1.50408051e+00,  9.62538827e-01, -9.68314855e-01,
        -3.82285822e-01],
       [-1.58100177e-01,  2.51850376e-01, -6.13279774e-01,
        -1.58432387e+00],
       [ 6.11326212e-01, -2.51068828e+00, -1.51057456e+00,
         4.53057350e-01],
       [-5.00265634e-01, -1.38378416e-01, -3.21998493e-01,
        -1.43599957e-01],
       [ 6.27746532e-04, -2.71728206e-02, -1.02827154e+00,
        -3.50335906e-01],
       [ 3.52062063e-01, -1.76159171e+00,  1.85921998e-03,
         1.38992412e+00],
       [ 5.13989437e-01, -3.71683998e-01, -1.42375092e+00,
        -4.70270654e-01]])

In [85]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [86]:
data[names == 'Bob']


array([[ 1.50408051,  0.96253883, -0.96831485, -0.38228582],
       [-0.50026563, -0.13837842, -0.32199849, -0.14359996]])

In [87]:
data[names == 'Bob', 2:]


array([[-0.96831485, -0.38228582],
       [-0.32199849, -0.14359996]])

In [88]:
data[names == 'Bob', 3]

array([-0.38228582, -0.14359996])

In [89]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [90]:
data[~(names == 'Bob')]

array([[-1.58100177e-01,  2.51850376e-01, -6.13279774e-01,
        -1.58432387e+00],
       [ 6.11326212e-01, -2.51068828e+00, -1.51057456e+00,
         4.53057350e-01],
       [ 6.27746532e-04, -2.71728206e-02, -1.02827154e+00,
        -3.50335906e-01],
       [ 3.52062063e-01, -1.76159171e+00,  1.85921998e-03,
         1.38992412e+00],
       [ 5.13989437e-01, -3.71683998e-01, -1.42375092e+00,
        -4.70270654e-01]])

In [91]:
mask = (names == 'Bob') | (names == 'Will')
mask


array([ True, False,  True,  True,  True, False, False])

In [92]:
data[mask]

array([[ 1.50408051e+00,  9.62538827e-01, -9.68314855e-01,
        -3.82285822e-01],
       [ 6.11326212e-01, -2.51068828e+00, -1.51057456e+00,
         4.53057350e-01],
       [-5.00265634e-01, -1.38378416e-01, -3.21998493e-01,
        -1.43599957e-01],
       [ 6.27746532e-04, -2.71728206e-02, -1.02827154e+00,
        -3.50335906e-01]])

In [93]:
data[data < 0] = 0
data


array([[1.50408051e+00, 9.62538827e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.51850376e-01, 0.00000000e+00, 0.00000000e+00],
       [6.11326212e-01, 0.00000000e+00, 0.00000000e+00, 4.53057350e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.27746532e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.52062063e-01, 0.00000000e+00, 1.85921998e-03, 1.38992412e+00],
       [5.13989437e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [94]:
data[names != 'Joe'] = 7
data

array([[7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [0.00000000e+00, 2.51850376e-01, 0.00000000e+00, 0.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [3.52062063e-01, 0.00000000e+00, 1.85921998e-03, 1.38992412e+00],
       [5.13989437e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

# Transposing Arrays and Swapping Axes

In [96]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [98]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Concatenating and Splitting Arrays

In [99]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])