In [1]:
import numpy as np

# Q 2

In [2]:
Data1 = np.array([1,3,9,12,18])
Data2 = np.array([[1,5,2,0],[3,6,4,7]])
Data3 = np.array([[7,6],[5,4],[3,2]], dtype= '<U1')
Data4 = np.array([[11,52,20,50],[34,61,43,17]])

print("Data1:\n", Data1)
print("Data2:\n", Data2)
print("Data3:\n", Data3)
print("Data4:\n", Data4)

Data1:
 [ 1  3  9 12 18]
Data2:
 [[1 5 2 0]
 [3 6 4 7]]
Data3:
 [['7' '6']
 ['5' '4']
 ['3' '2']]
Data4:
 [[11 52 20 50]
 [34 61 43 17]]


# Q3

### Add Data1 in Data1

In [3]:
Data1+Data1

array([ 2,  6, 18, 24, 36])

### Multiply Data1 by 10

In [4]:
Data1*10

array([ 10,  30,  90, 120, 180])

### Convert Data1, Data2, Data3, and Data4 datatypes to integer.

In [5]:
Data1.astype('int32')
Data2.astype('int32')
Data3.astype('int32')
Data4.astype('int32')
print(Data1.dtype)
print(Data2.dtype)
print(Data3.dtype)
print(Data4.dtype)

int32
int32
<U1
int32


# Q4

### 3x5 array of 0s

In [6]:
np.zeros((3, 5), np.dtype('int32'))

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 2x8 array of 1s

In [7]:
np.ones((2, 8), np.dtype('int32'))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

### 6x3 array of integer random numbers

In [8]:
np.random.randn(6, 3).astype(np.int32)

array([[-2,  0,  0],
       [-1,  1,  0],
       [ 0,  1, -1],
       [ 0,  0, -1],
       [ 1,  0,  0],
       [ 0,  0,  0]])

# Q5

Square the bold elements of Data1 and Data2. Hint: use indexing and slicing

In [9]:
Data1[[2,3]] = Data1[[2,3]]**2
Data1

array([  1,   3,  81, 144,  18])

In [10]:
Data2[0, 1] = Data2[0, 1] ** 2      # Square the element at row 0, column 1 (5)
Data2[1, 2] = Data2[1, 2] ** 2      # Square the element at row 1, column 2 (4)
Data2

array([[ 1, 25,  2,  0],
       [ 3,  6, 16,  7]])

# Q6

In [11]:
subject_of_CIS = np.array(['ML', 'OS', 'CCN', 'OS', 'AI', 'MP', 'CCN', 'ML', 'AI']).reshape(3, 3)
print(subject_of_CIS)
# This line filters out values that are neither 'ML' nor 'AI' and sets them to '0'.
subject_of_CIS[(subject_of_CIS != 'ML') & (subject_of_CIS != 'AI')] = '0'
subject_of_CIS

[['ML' 'OS' 'CCN']
 ['OS' 'AI' 'MP']
 ['CCN' 'ML' 'AI']]


array([['ML', '0', '0'],
       ['0', 'AI', '0'],
       ['0', 'ML', 'AI']], dtype='<U3')

# Q 7

### Transpose the Data2, Data3, and Data4 arrays

In [12]:
Data2.T

array([[ 1,  3],
       [25,  6],
       [ 2, 16],
       [ 0,  7]])

In [13]:
Data3.T

array([['7', '5', '3'],
       ['6', '4', '2']], dtype='<U1')

In [14]:
Data4.T

array([[11, 34],
       [52, 61],
       [20, 43],
       [50, 17]])

# Q8

Concatenate Data2 and Data4 using vstack and hstack

In [15]:
np.vstack((Data2, Data4))

array([[ 1, 25,  2,  0],
       [ 3,  6, 16,  7],
       [11, 52, 20, 50],
       [34, 61, 43, 17]])

In [16]:
np.hstack((Data2, Data4))

array([[ 1, 25,  2,  0, 11, 52, 20, 50],
       [ 3,  6, 16,  7, 34, 61, 43, 17]])

# Q9

Demean each column of Data2. Hint: use broadcasting.

In [23]:
Data2 = np.array([[1, 5, 2, 0], [3, 6, 4, 7]])
Data2-Data2.mean(0)


array([[-1. , -0.5, -1. , -3.5],
       [ 1. ,  0.5,  1. ,  3.5]])

# Q 10

###  Convert Data2 shape into 4x2.

In [24]:
Data2 = np.array([[1,5,2,0],[3,6,4,7]])
Data2.reshape(4,2)

array([[1, 5],
       [2, 0],
       [3, 6],
       [4, 7]])

# Q 11

In [32]:
Students_Scores=np.array([['Subjects','Student1','Student2','Student3',],['Subject1(2CH)',60,70,50],['Subject2(3CH)',40,60,80],
                          ['Subject3(4CH)',70,55,65]])
print(Students_Scores)
Score=np.array([Students_Scores[1][1:],Students_Scores[2][1:],Students_Scores[3][1:]])
print()
print(Score)
Score=Score.astype(np.int32)
Score.max(axis=1)

[['Subjects' 'Student1' 'Student2' 'Student3']
 ['Subject1(2CH)' '60' '70' '50']
 ['Subject2(3CH)' '40' '60' '80']
 ['Subject3(4CH)' '70' '55' '65']]

[['60' '70' '50']
 ['40' '60' '80']
 ['70' '55' '65']]


array([70, 80, 70])

# Q 12

In [42]:
Student1=np.array([Students_Scores[1][1],Students_Scores[2][1],Students_Scores[3][1]]).astype(np.int32)
print(Student1)
Student2=np.array([Students_Scores[1][2],Students_Scores[2][2],Students_Scores[3][2]]).astype(np.int32)
print(Student2)
Student3=np.array([Students_Scores[1][3],Students_Scores[2][3],Students_Scores[3][3]]).astype(np.int32)
print(Student3)
weights = np.array([2, 3, 4])
Points = np.array([
    np.multiply(Student1, weights).sum() / 9,
    np.multiply(Student2, weights).sum() / 9,
    np.multiply(Student3, weights).sum() / 9
])
print("CGPA of Student 1:", Points[0])
print("CGPA of Student 2:", Points[1])
print("CGPA of Student 3:", Points[2])

[60 40 70]
[70 60 55]
[50 80 65]
CGPA of Student 1: 57.77777777777778
CGPA of Student 2: 60.0
CGPA of Student 3: 66.66666666666667


# Q 13

In [51]:
list_of_marks = np.array([Students_Scores[1][1:],Students_Scores[2][1:],Students_Scores[3][1:]])
np.unique(list_of_marks.ravel().astype(np.int32))


array([40, 50, 55, 60, 65, 70, 80])

# Q 14

In [52]:
matrix = np.random.rand(4, 4)
dot_product = np.dot(matrix, matrix)
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
else:
    inverse_matrix = "Matrix is not invertible"

# Output results
print("Random 4x4 Matrix:")
print(matrix)
print("\nDot Product of the matrix with itself:")
print(dot_product)
print("\nInverse of the matrix:")
print(inverse_matrix)


Random 4x4 Matrix:
[[0.85602532 0.06752292 0.61288961 0.51597951]
 [0.43588205 0.37650952 0.21051776 0.75918563]
 [0.14290324 0.81765649 0.57702407 0.88145555]
 [0.12172536 0.14964679 0.55866444 0.32161642]]

Dot Product of the matrix with itself:
[[0.91260308 0.6615722  1.18077526 1.19913639]
 [0.65973562 0.45693236 0.89201334 0.94047543]
 [0.66848468 0.92121917 1.08510977 1.48659984]
 [0.28841217 0.56948716 0.608146   0.77229247]]

Inverse of the matrix:
[[ 2.10092867 -1.37050507  0.96785599 -2.78807418]
 [ 1.7274008  -3.34865949  3.37648785 -4.12066407]
 [ 0.31786722 -1.15633714  0.20060858  1.66979666]
 [-2.15106369  4.08544385 -2.28584748  3.18132854]]
