In [2]:
import numpy as np

# Q 2

In [47]:
Data1 = np.array([1,3,9,12,18])
Data2 = np.array([[1,5,2,0],[3,6,4,7]])
Data3 = np.array([[7,6],[5,4],[3,2]], dtype= '<U1')
Data4 = np.array([[11,52,20,50],[34,61,43,17]])

print("Data1:\n", Data1)
print("Data2:\n", Data2)
print("Data3:\n", Data3)
print("Data4:\n", Data4)

Data1:
 [ 1  3  9 12 18]
Data2:
 [[1 5 2 0]
 [3 6 4 7]]
Data3:
 [['7' '6']
 ['5' '4']
 ['3' '2']]
Data4:
 [[11 52 20 50]
 [34 61 43 17]]


# Q3

### Add Data1 in Data1

In [7]:
Data1+Data1

array([ 2,  6, 18, 24, 36])

### Multiply Data1 by 10

In [8]:
Data1*10

array([ 10,  30,  90, 120, 180])

### Convert Data1, Data2, Data3, and Data4 datatypes to integer.

In [23]:
Data1.astype('int32')
Data2.astype('int32')
Data3.astype('int32')
Data4.astype('int32')
print(Data1.dtype)
print(Data2.dtype)
print(Data3.dtype)
print(Data4.dtype)

int32
int32
<U1
int32


# Q4

### 3x5 array of 0s

In [26]:
np.zeros((3, 5), np.dtype('int32'))

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 2x8 array of 1s

In [27]:
np.ones((2, 8), np.dtype('int32'))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

### 6x3 array of integer random numbers

In [31]:
np.random.randn(6, 3).astype(np.int32)

array([[ 1,  0,  1],
       [ 0,  0,  0],
       [ 1,  0,  0],
       [ 1,  0,  0],
       [ 0, -1,  1],
       [ 0,  0, -1]])

# Q5

Square the bold elements of Data1 and Data2. Hint: use indexing and slicing

In [32]:
Data1[[2,3]] = Data1[[2,3]]**2
Data1

array([  1,   3,  81, 144,  18])

In [33]:
Data2[0, 1] = Data2[0, 1] ** 2      # Square the element at row 0, column 1 (5)
Data2[1, 2] = Data2[1, 2] ** 2      # Square the element at row 1, column 2 (4)
Data2

array([[ 1, 25,  2,  0],
       [ 3,  6, 16,  7]])

# Q6

In [40]:
subject_of_CIS = np.array(['ML', 'OS', 'CCN','OS', 'AI', 'MP','CCN', 'ML', 'AI']).reshape(3,3)
print(subject_of_CIS )
# Create a Boolean mask for 'ML' and 'AI'
mask = (subject_of_CIS == 'ML') | (subject_of_CIS == 'AI')
# Set all other elements to 0
subject_of_CIS[~mask] = '0'
print(subject_of_CIS)

[['ML' 'OS' 'CCN']
 ['OS' 'AI' 'MP']
 ['CCN' 'ML' 'AI']]
[['ML' '0' '0']
 ['0' 'AI' '0']
 ['0' 'ML' 'AI']]


# Q 7

### Transpose the Data2, Data3, and Data4 arrays

In [48]:
Data2.T

array([[1, 3],
       [5, 6],
       [2, 4],
       [0, 7]])

In [49]:
Data3.T

array([['7', '5', '3'],
       ['6', '4', '2']], dtype='<U1')

In [50]:
Data4.T

array([[11, 34],
       [52, 61],
       [20, 43],
       [50, 17]])

# Q8

Concatenate Data2 and Data4 using vstack and hstack

In [51]:
np.vstack((Data2, Data4))

array([[ 1,  5,  2,  0],
       [ 3,  6,  4,  7],
       [11, 52, 20, 50],
       [34, 61, 43, 17]])

In [52]:
np.hstack((Data2, Data4))

array([[ 1,  5,  2,  0, 11, 52, 20, 50],
       [ 3,  6,  4,  7, 34, 61, 43, 17]])

# Q9

Demean each column of Data2. Hint: use broadcasting.

In [54]:
Data2 = np.array([[1, 5, 2, 0], [3, 6, 4, 7]])

column_means = Data2.mean(axis=0)
Data2_demeaned = Data2 - column_means
print("Demeaned Data2:\n", Data2_demeaned)

Demeaned Data2:
 [[-1.  -0.5 -1.  -3.5]
 [ 1.   0.5  1.   3.5]]
