In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
arr2.shape

# DTYPE

In [8]:
arr1.dtype

dtype('float64')

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr3= np.array([1,2,3] , dtype = np.float64)
arr3

array([1., 2., 3.])

In [11]:
arr4= np.array([1,2,3] , dtype = np.int32)
arr4

array([1, 2, 3])

In [12]:
arr3.dtype

dtype('float64')

In [13]:
arr4.dtype

dtype('int32')

# np.zeroes

In [16]:
np.zeros(10 , dtype= np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

2D array

In [20]:
np.zeros((3,6) , dtype = np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [21]:
np.empty((2,3,2))

array([[[1.17056368e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.37962456e-306, 2.21568772e+160]],

       [[9.44407405e+164, 2.62724591e+179],
        [4.85498974e-033, 3.08798753e-057],
        [1.24507654e-047, 2.83316095e-032]]])

# arange

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# array

In [25]:
np.array([1,8,9])

array([1, 8, 9])

In [26]:
np.array((1,8,9))

array([1, 8, 9])

# ones and ones_like

In [27]:
np.ones((2,3) , dtype =np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
tooba = np.array([[[1,2],[3,4],[5,6]]])
print(tooba)
np.ones_like(tooba)

[[[1 2]
  [3 4]
  [5 6]]]


array([[[1, 1],
        [1, 1],
        [1, 1]]])

# zeros, zeros_like

In [31]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
tooba = np.array([[[1,2],[3,4],[5,6]]])
print(tooba)
np.zeros_like(tooba)

[[[1 2]
  [3 4]
  [5 6]]]


array([[[0, 0],
        [0, 0],
        [0, 0]]])

# empty, empty_like

In [35]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# eye 

## np.eye(n, m, dtype, k for shift)

In [37]:
np.eye(3,4 ,dtype =np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [38]:
np.eye(3,4 ,dtype =np.int32 , k=1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

np.eye(3,4 ,dtype =np.int32 , k=2)

# identity dig me 0s

In [40]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

# Type Conversion for ndarrays

In [42]:
a= np.array([4,5,6])
a.dtype

dtype('int32')

In [43]:
b= a.astype(np.float32)
b.dtype

dtype('float32')

In [44]:
c= np.array([1.4, 7.8])
c.dtype

dtype('float64')

In [45]:
d= c.astype(np.int32)
d.dtype

dtype('int32')

In [46]:
d

array([1, 7])

In [47]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

[ 1.25 -9.6  42.  ]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Operations between Arrays and Scalars

In [48]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [49]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

## Basic Indexing and Slicing

In [50]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
arr


[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [51]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [52]:
arr_slice = arr[5:8]

In [53]:
arr_slice

array([12, 12, 12])

In [54]:
 arr_slice[1] = 12345

In [55]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 
12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
 arr3d[0]


array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
r= np.array([0,1,2,3,4,5,6,7,8,9,67])
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 67])