In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(f'{'C:/Users/Tesla Laptops/Downloads'}/D3_Heart_Dataset.csv')
data

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40      M           ATA        140          289          0     Normal   
1     49      F           NAP        160          180          0     Normal   
2     37      M           ATA        130          283          0         ST   
3     48      F           ASY        138          214          0     Normal   
4     54      M           NAP        150          195          0     Normal   
..   ...    ...           ...        ...          ...        ...        ...   
913   45      M            TA        110          264          0     Normal   
914   68      M           ASY        144          193          1     Normal   
915   57      M           ASY        130          131          0     Normal   
916   57      F           ATA        130          236          0        LVH   
917   38      M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Gender          918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [5]:
X = data.drop("HeartDisease",axis=1)

In [6]:
Y = data["HeartDisease"] 

In [7]:
X['Gender'].unique()

array(['M', 'F'], dtype=object)

In [8]:
X['Gender'] = X['Gender'].replace('M',0)
X['Gender'] = X['Gender'].replace('F',1)

C:\Users\Tesla Laptops\AppData\Local\Temp\ipykernel_16196\1989171357.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['Gender'] = X['Gender'].replace('F',1)


In [9]:
X['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [10]:
X['ChestPainType'] = X['ChestPainType'].replace('ATA',0)
X['ChestPainType'] = X['ChestPainType'].replace('NAP',1)
X['ChestPainType'] = X['ChestPainType'].replace('ASY',2)
X['ChestPainType'] = X['ChestPainType'].replace('TA',3)

C:\Users\Tesla Laptops\AppData\Local\Temp\ipykernel_16196\834497296.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['ChestPainType'] = X['ChestPainType'].replace('TA',3)


In [11]:
X['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [12]:
X['RestingECG'] = X['RestingECG'].replace('Normal',0)
X['RestingECG'] = X['RestingECG'].replace('ST',1)
X['RestingECG'] = X['RestingECG'].replace('LVH',2)

C:\Users\Tesla Laptops\AppData\Local\Temp\ipykernel_16196\2060767386.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['RestingECG'] = X['RestingECG'].replace('LVH',2)


In [13]:
X['ExerciseAngina'].unique()

array(['N', 'Y'], dtype=object)

In [14]:
X['ExerciseAngina'] = X['ExerciseAngina'].replace('N',0)
X['ExerciseAngina'] = X['ExerciseAngina'].replace('Y',1)

C:\Users\Tesla Laptops\AppData\Local\Temp\ipykernel_16196\2839445076.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['ExerciseAngina'] = X['ExerciseAngina'].replace('Y',1)


In [15]:
X['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [16]:
X['ST_Slope'] = X['ST_Slope'].replace('Up',0)
X['ST_Slope'] = X['ST_Slope'].replace('Flat',1)
X['ST_Slope'] = X['ST_Slope'].replace('Down',2)

C:\Users\Tesla Laptops\AppData\Local\Temp\ipykernel_16196\2025370437.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['ST_Slope'] = X['ST_Slope'].replace('Down',2)


In [17]:
X

Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  \
0     40       0              0        140          289          0   
1     49       1              1        160          180          0   
2     37       0              0        130          283          0   
3     48       1              2        138          214          0   
4     54       0              1        150          195          0   
..   ...     ...            ...        ...          ...        ...   
913   45       0              3        110          264          0   
914   68       0              2        144          193          1   
915   57       0              2        130          131          0   
916   57       1              0        130          236          0   
917   38       0              1        138          175          0   

     RestingECG  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
0             0    172               0      0.0         0  
1             0    156               0      1.0         1  
2             1     98               0      0.0         0  
3             0    108               1      1.5         1  
4             0    122               0      0.0         0  
..          ...    ...             ...      ...       ...  
913           0    132               0      1.2         1  
914           0    141               0      3.4         1  
915           0    115               1      1.2         1  
916           2    174               0      0.0         1  
917           0    173               0      0.0         0  

[918 rows x 11 columns]

In [18]:
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics 
from sklearn.metrics import confusion_matrix, classification_report

X_train,X_test,Y_train,Y_test = train_test_split(X, Y,test_size=0.20,random_state=0) 
print(X_train.shape )
print(X_test.shape) 
print(Y_train.shape) 
print(Y_test.shape)

(734, 11)
(184, 11)
(734,)
(184,)


In [19]:
# Creating Gaussian Naive Bayes Object
classifer1 = GaussianNB() 
# Training the model
model1 = classifer1.fit(X_train, Y_train) 

In [20]:
# Evaluating the model
Y_pred1 = model1.predict(X_test) 
print("The accuracy is "+str(metrics.accuracy_score(Y_test,Y_pred1)*100)+"%") 
print(confusion_matrix(Y_test, Y_pred1))

The accuracy is 83.15217391304348%
[[60 17]
 [14 93]]


In [21]:
target_names = ['class 0', 'class 1'] 
print(classification_report(Y_test, Y_pred1, target_names=target_names)) 

              precision    recall  f1-score   support

     class 0       0.81      0.78      0.79        77
     class 1       0.85      0.87      0.86       107

    accuracy                           0.83       184
   macro avg       0.83      0.82      0.83       184
weighted avg       0.83      0.83      0.83       184



In [22]:
# Creating Gaussian Naive Bayes Object
classifer2 = GaussianNB(priors=[0.25, 0.75]) 
# Training the model
model2 = classifer2.fit(X_train, Y_train) 

# Evaluating the model
Y_pred2 = model2.predict(X_test) 
print("The accuracy is "+str(metrics.accuracy_score(Y_test,Y_pred2)*100)+"%") 
print(confusion_matrix(Y_test, Y_pred2))

The accuracy is 84.23913043478261%
[[58 19]
 [10 97]]


In [23]:
# from sklearn.naive_bayes import MultinomialNB

# # Creating Multinomial Naive Bayes Object
# classifer3 = MultinomialNB() 

# # Training the model
# model3 = classifer3.fit(X_train, Y_train) 

# # Evaluating the model
# Y_pred3 = model3.predict(X_test) 
# print("The accuracy is "+str(metrics.accuracy_score(Y_test,Y_pred3)*100)+"%") 
# print(confusion_matrix(Y_test, Y_pred3))

# Method 1 repalce neg val with abs 
# 1 CALCULATING NEG VALUES PER COLUMN

In [24]:
r= X_train.copy()
# Boolean mask for negative values and is applied element wise to the DF
negative_values = r < 0

# Count the number of negative values in each column
neg_count_per_column = negative_values.sum()
print("Negative values count per column:")
print(neg_count_per_column)


Negative values count per column:
Age                0
Gender             0
ChestPainType      0
RestingBP          0
Cholesterol        0
FastingBS          0
RestingECG         0
MaxHR              0
ExerciseAngina     0
Oldpeak           11
ST_Slope           0
dtype: int64


# 2 Find the indices of negative values for each column

In [25]:
for column in r.columns:
    if neg_count_per_column[column] > 0:  # Only process columns with negative values
        print(f"Column: {column}")
        print("Indices of negative values:", r[r[column] < 0].index.tolist())


Column: Oldpeak
Indices of negative values: [331, 352, 334, 325, 407, 421, 326, 512, 324, 321, 335]


# 3 Find the indices and the corresponding negative values for each column

In [26]:
for column in r.columns:
    if neg_count_per_column[column] > 0:  # Only process columns with negative values
        # Get indices where the column has negative values
        indices = r[r[column] < 0].index.tolist()
        
        # Get the negative values at those indices
        values = r.loc[indices, column].tolist()
        
        # Print the results
        print(f"\nColumn: {column}")
        print("Indices of negative values:", indices)
        print("Negative values at these indices:", values)



Column: Oldpeak
Indices of negative values: [331, 352, 334, 325, 407, 421, 326, 512, 324, 321, 335]
Negative values at these indices: [-1.0, -1.0, -0.7, -1.5, -0.5, -0.5, -0.1, -0.1, -2.6, -0.9, -0.8]


# 4 Replace negative values in the DataFrame with their positive counterparts

In [27]:
for column in r.columns:
    if neg_count_per_column[column] > 0:  # Only process columns with negative values
        # Replace negative values with their absolute values
        r[column] = r[column].apply(lambda x: abs(x) if x < 0 else x)

# Print the updated DataFrame
print("Updated DataFrame:")
print(r)


Updated DataFrame:
     Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  \
378   70       0              2        140            0          1   
356   46       0              2        115            0          0   
738   65       1              1        160          360          0   
85    66       0              2        140          139          0   
427   59       0              2        140            0          0   
..   ...     ...            ...        ...          ...        ...   
835   54       0              2        110          239          0   
192   48       0              0        130          245          0   
629   57       1              2        128          303          0   
559   64       0              2        134          273          0   
684   47       0              1        108          243          0   

     RestingECG  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
378           0    157               1      2.0         1  
356           0    1

# VERIFAICATION THAT X_TRAIN HAS NO NEG VALUES

In [28]:
import numpy as np

# Check for negative values in X_train
print("Minimum value in X_train:", np.min(r))
print("Minimum value in X_test:", np.min(X_test))


Minimum value in X_train: 0.0
Minimum value in X_test: -2.0


In [29]:
s= X_test.copy()
# Boolean mask for negative values and is applied element wise to the DF
negative_values = s < 0

# Count the number of negative values in each column
neg_count_per_column = negative_values.sum()
print("Negative values count per column:")
print(neg_count_per_column)

for column in s.columns:
    if neg_count_per_column[column] > 0:  # Only process columns with negative values
        print(f"Column: {column}")
        print("Indices of negative values:", s[s[column] < 0].index.tolist())

for column in s.columns:
    if neg_count_per_column[column] > 0:  # Only process columns with negative values
        # Get indices where the column has negative values
        indices = s[s[column] < 0].index.tolist()
        
        # Get the negative values at those indices
        values = s.loc[indices, column].tolist()
        
        # Print the results
        print(f"\nColumn: {column}")
        print("Indices of negative values:", indices)
        print("Negative values at these indices:", values)

for column in s.columns:
    if neg_count_per_column[column] > 0:  # Only process columns with negative values
        # Replace negative values with their absolute values
        s[column] = s[column].apply(lambda x: abs(x) if x < 0 else x)

# Print the updated DataFrame
print("Updated DataFrame:")
print(s)

Negative values count per column:
Age               0
Gender            0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           2
ST_Slope          0
dtype: int64
Column: Oldpeak
Indices of negative values: [332, 413]

Column: Oldpeak
Indices of negative values: [332, 413]
Negative values at these indices: [-1.1, -2.0]
Updated DataFrame:
     Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  \
306   55       0              2        115            0          1   
711   66       0              2        120          302          0   
298   51       0              2        110            0          1   
466   55       0              1        120            0          0   
253   62       0              0        140          271          0   
..   ...     ...            ...        ...          ...        ...   
909   63       1              2        124          197          0

In [30]:
# Check for negative values in X_train
print("Minimum value in X_train:", np.min(r))
print("Minimum value in X_test:", np.min(s))
print("Minimum value in :", np.min(Y_test))
print("Minimum value in :", np.min(Y_train))

Minimum value in X_train: 0.0
Minimum value in X_test: 0.0
Minimum value in : 0
Minimum value in : 0


In [31]:
from sklearn.naive_bayes import MultinomialNB

# Creating Multinomial Naive Bayes Object
classifer3 = MultinomialNB() 

# Training the model
model3 = classifer3.fit(r, Y_train) 

# Evaluating the model
Y_pred3 = model3.predict(s) 
print("The accuracy is "+str(metrics.accuracy_score(Y_test,Y_pred3)*100)+"%") 
print(confusion_matrix(Y_test, Y_pred3))

The accuracy is 67.93478260869566%
[[65 12]
 [47 60]]


# 2 method scale 

In [32]:
from sklearn.preprocessing import MinMaxScaler
a= X_train.copy()
b= X_test.copy()

# Scale data to [0, 1]
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(a)
X_test_scaled = scaler.transform(b)

# Use MultinomialNB with scaled data
from sklearn.naive_bayes import MultinomialNB

classifier = MultinomialNB()
model = classifier.fit(X_train_scaled, Y_train)
Y_pred = model.predict(X_test_scaled)

# Evaluate
print("Accuracy:", metrics.accuracy_score(Y_test, Y_pred) * 100, "%")


Accuracy: 80.97826086956522 %


# 3 Method drop continous valued column

In [33]:
R = X.copy()  # Make a copy of X first, so X isn't affected
R.drop("Age", axis=1, inplace=True)
R.drop("RestingBP", axis=1, inplace=True)
R.drop("Cholesterol", axis=1, inplace=True)
R.drop("Oldpeak", axis=1, inplace=True)
R.drop("MaxHR", axis=1, inplace=True)

In [34]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics 
from sklearn.metrics import confusion_matrix, classification_report

X_train,X_test,Y_train,Y_test = train_test_split(R, Y,test_size=0.20,random_state=0) 
print(X_train.shape )
print(X_test.shape) 
print(Y_train.shape) 
print(Y_test.shape)

# Creating Multinomial Naive Bayes Object
classifer4 = MultinomialNB() 

# Training the model
model4 = classifer4.fit(X_train, Y_train) 

# Evaluating the model
Y_pred4 = model4.predict(X_test) 
print("The accuracy is "+str(metrics.accuracy_score(Y_test,Y_pred4)*100)+"%") 
print(confusion_matrix(Y_test, Y_pred4))

(734, 6)
(184, 6)
(734,)
(184,)
The accuracy is 70.65217391304348%
[[39 38]
 [16 91]]
